background = #080b0d
foreground = #d7d5ce
cursor-color = #e6e2d8
selection-background = #c7d9d4
selection-foreground = #080b0d
palette = 0=#080b0d
palette = 1=#d79894
palette = 2=#a4c4ad
palette = 3=#d9c49c
palette = 4=#a9bbc9
palette = 5=#bca9c2
palette = 6=#a9c3c1
palette = 7=#d7d5ce
palette = 8=#8a969c
palette = 9=#efb7ad
palette = 10=#c0ddc5
palette = 11=#efdbb5
palette = 12=#c8d7e3
palette = 13=#d8c6df
palette = 14=#c7e0dc
palette = 15=#f3f0e8
