$color = rgba(8, 11, 13, 1)
$inner_color = rgba(20, 27, 30, 0.96)
$outer_color = rgba(200, 157, 124, 1)
$font_color = rgba(215, 213, 206, 1)
$placeholder_color = rgba(138, 150, 156, 1)
$check_color = rgba(169, 195, 193, 1)
