background #080b0d
foreground #d7d5ce
cursor #e6e2d8
selection_background #c7d9d4
selection_foreground #080b0d
color0 #080b0d
color1 #d79894
color2 #a4c4ad
color3 #d9c49c
color4 #a9bbc9
color5 #bca9c2
color6 #a9c3c1
color7 #d7d5ce
color8 #8a969c
color9 #efb7ad
color10 #c0ddc5
color11 #efdbb5
color12 #c8d7e3
color13 #d8c6df
color14 #c7e0dc
color15 #f3f0e8
